name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0' # weekly

env:
  # default compiler for all non-compatibility tests
  MATRIX_EVAL: "CC=gcc-11 && CXX=g++-11"

jobs:


  Build:
    name: 'B: Building VtR'
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        BUILD_TYPE: release
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh


  Format:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - { name: 'C/C++',       script: 'check-format.sh'    }
        - { name: 'Python',      script: 'check-format-py.sh' }
        - { name: 'Python Lint', script: 'pylint_check.py'    }
    name: 'F: ${{ matrix.name }}'
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      run: |
        source .github/travis/common.sh
        ./dev/${{ matrix.script }}


  UniTests:
    name: 'U: C++ Unit Tests'
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: "-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on"
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh
        ./.github/travis/unittest.sh


  Warnings:
    name: 'W: Check Compilation Warnings'
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        #In order to get compilation warnings produced per source file, we must do a non-IPO build
        #We also turn warnings into errors for this target by doing a strict compile
        CMAKE_PARAMS: "-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on -DVTR_ENABLE_STRICT_COMPILE=on -DVTR_IPO_BUILD=off"
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh


  Regression:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include: [
          {
            name: 'Basic',
            params: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on',
            suite: 'vtr_reg_basic'
          },
          {
            name: 'Basic with NO_GRAPHICS',
            params: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on -DVPR_USE_EZGL=off',
            suite: 'vtr_reg_basic'
          },
          {
            name: 'Basic with VTR_ENABLE_DEBUG_LOGGING',
            params: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on -DVTR_ENABLE_DEBUG_LOGGING=on',
            suite: 'vtr_reg_basic'
          },
          {
            name: 'Strong',
            params: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on',
            suite: 'vtr_reg_strong'
          },
          {
            name: 'Valgrind Memory',
            params: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on',
            suite: 'vtr_reg_valgrind_small'
          }
        ]
    name: 'R: ${{ matrix.name }}'
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: ${{ matrix.params }}
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh
        ./run_reg_test.py ${{ matrix.suite }} -show_failures -j2


  Sanitized:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - { name: 'Basic',  suite: 'vtr_reg_basic'  }
        #- { name: 'Strong', suite: 'vtr_reg_strong' } # SKIP Too long to run on GitHub Actions (max 6h)
    name: 'S: ${{ matrix.name }}'
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: '-DVTR_ASSERT_LEVEL=3 -DVTR_ENABLE_SANITIZE=on -DVTR_IPO_BUILD=off -DWITH_BLIFEXPLORER=on'
        BUILD_TYPE: debug
        LSAN_OPTIONS: 'exitcode=42' #Use a non-standard exit code to ensure LSAN errors are detected
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh
        # We skip QoR since we are only checking for errors in sanitizer runs
        ./run_reg_test.py ${{ matrix.suite }} -show_failures -j2 -skip_qor


  ODINII:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include: [
          {
            name: 'Odin Reg Basic',
            suite: 'odin_reg_basic'
          },
          {
            name: 'Odin Tech Basic',
            suite: 'odin_tech_basic'
          }
        ]
    name: 'R: ${{ matrix.name }}'
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - run: ./.github/gha/install_yosys.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: '-DVTR_ASSERT_LEVEL=3 -DVTR_ENABLE_SANITIZE=on -DVTR_IPO_BUILD=off -DWITH_BLIFEXPLORER=on'
        BUILD_TYPE: debug
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh
        ./run_reg_test.py ${{ matrix.suite }} -show_failures -j2


  Compatibility:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - { name: 'GCC 7 (Ubuntu Bionic - 18.04)',    eval: 'CC=gcc-7 && CXX=g++-7',           build: ''               }
        - { name: 'GCC 8 (Debian Buster)',            eval: 'CC=gcc-8 && CXX=g++-8',           build: ''               }
        - { name: 'GCC 9 (Ubuntu Focal - 20.04)',     eval: 'CC=gcc-9 && CXX=g++-9',           build: ''               }
        - { name: 'GCC 10 (Ubuntu Hirsute - 21.04)',  eval: 'CC=gcc-10 && CXX=g++-10',         build: ''               }
        - { name: 'GCC 11 (Latest)',                  eval: 'CC=gcc-11 && CXX=g++-11',         build: ''               }
        - { name: 'Clang 6 (Ubuntu Bionic - 18.04)',  eval: 'CC=clang-6.0 && CXX=clang++-6.0', build: ''               }
        - { name: 'Clang 7 (Debian Buster)',          eval: 'CC=clang-7 && CXX=clang++-7',     build: ''               }
        - { name: 'Clang 10 (Ubuntu Focal - 20.04)',  eval: 'CC=clang-10 && CXX=clang++-10',   build: ''               }
    name: 'B: ${{ matrix.name }}'
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: "-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on"
        MATRIX_EVAL: ${{ matrix.eval }}
        BUILD_TYPE: ${{ matrix.build }}
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh


  Coverity:
    name: 'Coverity Scan'
    needs:
      - Build
      - Format
      - UniTests
      - Warnings
      - Regression
      - Sanitized
      - ODINII
      - Compatibility
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - run: ./.github/gha/install_dependencies.sh
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install -r requirements.txt

    - name: Test
      env:
        CMAKE_PARAMS: '-DVTR_ASSERT_LEVEL=3 -DWITH_BLIFEXPLORER=on'
        _COVERITY_URL: 'https://scan.coverity.com/download/linux64'
        _COVERITY_MD5: 'd0d7d7df9d6609e578f85096a755fb8f'
      run: |
        source .github/travis/common.sh
        ./.github/travis/build.sh
